//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsDatos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsDatos.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        wsDatos.CompositeType GetDataUsingDataContract(wsDatos.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<wsDatos.CompositeType> GetDataUsingDataContractAsync(wsDatos.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerDatos", ReplyAction="http://tempuri.org/IService1/ObtenerDatosResponse")]
        string ObtenerDatos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerDatos", ReplyAction="http://tempuri.org/IService1/ObtenerDatosResponse")]
        System.Threading.Tasks.Task<string> ObtenerDatosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstado", ReplyAction="http://tempuri.org/IService1/ObtenerEstadoResponse")]
        string ObtenerEstado(int idEquipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstado", ReplyAction="http://tempuri.org/IService1/ObtenerEstadoResponse")]
        System.Threading.Tasks.Task<string> ObtenerEstadoAsync(int idEquipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerDatosGraficas", ReplyAction="http://tempuri.org/IService1/ObtenerDatosGraficasResponse")]
        string ObtenerDatosGraficas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerDatosGraficas", ReplyAction="http://tempuri.org/IService1/ObtenerDatosGraficasResponse")]
        System.Threading.Tasks.Task<string> ObtenerDatosGraficasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarLogin", ReplyAction="http://tempuri.org/IService1/ValidarLoginResponse")]
        string ValidarLogin(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarLogin", ReplyAction="http://tempuri.org/IService1/ValidarLoginResponse")]
        System.Threading.Tasks.Task<string> ValidarLoginAsync(string usuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerResumenDashboard", ReplyAction="http://tempuri.org/IService1/ObtenerResumenDashboardResponse")]
        string ObtenerResumenDashboard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerResumenDashboard", ReplyAction="http://tempuri.org/IService1/ObtenerResumenDashboardResponse")]
        System.Threading.Tasks.Task<string> ObtenerResumenDashboardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProgramasActivos", ReplyAction="http://tempuri.org/IService1/ObtenerProgramasActivosResponse")]
        string ObtenerProgramasActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerProgramasActivos", ReplyAction="http://tempuri.org/IService1/ObtenerProgramasActivosResponse")]
        System.Threading.Tasks.Task<string> ObtenerProgramasActivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerInscripcionesPorPrograma", ReplyAction="http://tempuri.org/IService1/ObtenerInscripcionesPorProgramaResponse")]
        string ObtenerInscripcionesPorPrograma(int idPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerInscripcionesPorPrograma", ReplyAction="http://tempuri.org/IService1/ObtenerInscripcionesPorProgramaResponse")]
        System.Threading.Tasks.Task<string> ObtenerInscripcionesPorProgramaAsync(int idPrograma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerResumenFinanzas", ReplyAction="http://tempuri.org/IService1/ObtenerResumenFinanzasResponse")]
        string ObtenerResumenFinanzas(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerResumenFinanzas", ReplyAction="http://tempuri.org/IService1/ObtenerResumenFinanzasResponse")]
        System.Threading.Tasks.Task<string> ObtenerResumenFinanzasAsync(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEgresosPorAnio", ReplyAction="http://tempuri.org/IService1/ObtenerEgresosPorAnioResponse")]
        string ObtenerEgresosPorAnio(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEgresosPorAnio", ReplyAction="http://tempuri.org/IService1/ObtenerEgresosPorAnioResponse")]
        System.Threading.Tasks.Task<string> ObtenerEgresosPorAnioAsync(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerFinanzasPorAnio", ReplyAction="http://tempuri.org/IService1/ObtenerFinanzasPorAnioResponse")]
        string ObtenerFinanzasPorAnio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerFinanzasPorAnio", ReplyAction="http://tempuri.org/IService1/ObtenerFinanzasPorAnioResponse")]
        System.Threading.Tasks.Task<string> ObtenerFinanzasPorAnioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerResumenDesercion", ReplyAction="http://tempuri.org/IService1/ObtenerResumenDesercionResponse")]
        string ObtenerResumenDesercion(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerResumenDesercion", ReplyAction="http://tempuri.org/IService1/ObtenerResumenDesercionResponse")]
        System.Threading.Tasks.Task<string> ObtenerResumenDesercionAsync(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMotivosBajas", ReplyAction="http://tempuri.org/IService1/ObtenerMotivosBajasResponse")]
        string ObtenerMotivosBajas(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMotivosBajas", ReplyAction="http://tempuri.org/IService1/ObtenerMotivosBajasResponse")]
        System.Threading.Tasks.Task<string> ObtenerMotivosBajasAsync(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerBajasPorMes", ReplyAction="http://tempuri.org/IService1/ObtenerBajasPorMesResponse")]
        string ObtenerBajasPorMes(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerBajasPorMes", ReplyAction="http://tempuri.org/IService1/ObtenerBajasPorMesResponse")]
        System.Threading.Tasks.Task<string> ObtenerBajasPorMesAsync(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerIngresosPorTipo", ReplyAction="http://tempuri.org/IService1/ObtenerIngresosPorTipoResponse")]
        string ObtenerIngresosPorTipo(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerIngresosPorTipo", ReplyAction="http://tempuri.org/IService1/ObtenerIngresosPorTipoResponse")]
        System.Threading.Tasks.Task<string> ObtenerIngresosPorTipoAsync(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTopProgramasRentables", ReplyAction="http://tempuri.org/IService1/ObtenerTopProgramasRentablesResponse")]
        string ObtenerTopProgramasRentables(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerTopProgramasRentables", ReplyAction="http://tempuri.org/IService1/ObtenerTopProgramasRentablesResponse")]
        System.Threading.Tasks.Task<string> ObtenerTopProgramasRentablesAsync(int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerBajasPorPrograma", ReplyAction="http://tempuri.org/IService1/ObtenerBajasPorProgramaResponse")]
        string ObtenerBajasPorPrograma(int idPrograma, int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerBajasPorPrograma", ReplyAction="http://tempuri.org/IService1/ObtenerBajasPorProgramaResponse")]
        System.Threading.Tasks.Task<string> ObtenerBajasPorProgramaAsync(int idPrograma, int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMotivosBajasPorPrograma", ReplyAction="http://tempuri.org/IService1/ObtenerMotivosBajasPorProgramaResponse")]
        string ObtenerMotivosBajasPorPrograma(int idPrograma, int anio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerMotivosBajasPorPrograma", ReplyAction="http://tempuri.org/IService1/ObtenerMotivosBajasPorProgramaResponse")]
        System.Threading.Tasks.Task<string> ObtenerMotivosBajasPorProgramaAsync(int idPrograma, int anio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IService1Channel : wsDatos.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<wsDatos.IService1>, wsDatos.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public wsDatos.CompositeType GetDataUsingDataContract(wsDatos.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<wsDatos.CompositeType> GetDataUsingDataContractAsync(wsDatos.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string ObtenerDatos()
        {
            return base.Channel.ObtenerDatos();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerDatosAsync()
        {
            return base.Channel.ObtenerDatosAsync();
        }
        
        public string ObtenerEstado(int idEquipo)
        {
            return base.Channel.ObtenerEstado(idEquipo);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerEstadoAsync(int idEquipo)
        {
            return base.Channel.ObtenerEstadoAsync(idEquipo);
        }
        
        public string ObtenerDatosGraficas()
        {
            return base.Channel.ObtenerDatosGraficas();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerDatosGraficasAsync()
        {
            return base.Channel.ObtenerDatosGraficasAsync();
        }
        
        public string ValidarLogin(string usuario, string contrasena)
        {
            return base.Channel.ValidarLogin(usuario, contrasena);
        }
        
        public System.Threading.Tasks.Task<string> ValidarLoginAsync(string usuario, string contrasena)
        {
            return base.Channel.ValidarLoginAsync(usuario, contrasena);
        }
        
        public string ObtenerResumenDashboard()
        {
            return base.Channel.ObtenerResumenDashboard();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerResumenDashboardAsync()
        {
            return base.Channel.ObtenerResumenDashboardAsync();
        }
        
        public string ObtenerProgramasActivos()
        {
            return base.Channel.ObtenerProgramasActivos();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerProgramasActivosAsync()
        {
            return base.Channel.ObtenerProgramasActivosAsync();
        }
        
        public string ObtenerInscripcionesPorPrograma(int idPrograma)
        {
            return base.Channel.ObtenerInscripcionesPorPrograma(idPrograma);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerInscripcionesPorProgramaAsync(int idPrograma)
        {
            return base.Channel.ObtenerInscripcionesPorProgramaAsync(idPrograma);
        }
        
        public string ObtenerResumenFinanzas(int anio)
        {
            return base.Channel.ObtenerResumenFinanzas(anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerResumenFinanzasAsync(int anio)
        {
            return base.Channel.ObtenerResumenFinanzasAsync(anio);
        }
        
        public string ObtenerEgresosPorAnio(int anio)
        {
            return base.Channel.ObtenerEgresosPorAnio(anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerEgresosPorAnioAsync(int anio)
        {
            return base.Channel.ObtenerEgresosPorAnioAsync(anio);
        }
        
        public string ObtenerFinanzasPorAnio()
        {
            return base.Channel.ObtenerFinanzasPorAnio();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerFinanzasPorAnioAsync()
        {
            return base.Channel.ObtenerFinanzasPorAnioAsync();
        }
        
        public string ObtenerResumenDesercion(int anio)
        {
            return base.Channel.ObtenerResumenDesercion(anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerResumenDesercionAsync(int anio)
        {
            return base.Channel.ObtenerResumenDesercionAsync(anio);
        }
        
        public string ObtenerMotivosBajas(int anio)
        {
            return base.Channel.ObtenerMotivosBajas(anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerMotivosBajasAsync(int anio)
        {
            return base.Channel.ObtenerMotivosBajasAsync(anio);
        }
        
        public string ObtenerBajasPorMes(int anio)
        {
            return base.Channel.ObtenerBajasPorMes(anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerBajasPorMesAsync(int anio)
        {
            return base.Channel.ObtenerBajasPorMesAsync(anio);
        }
        
        public string ObtenerIngresosPorTipo(int anio)
        {
            return base.Channel.ObtenerIngresosPorTipo(anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerIngresosPorTipoAsync(int anio)
        {
            return base.Channel.ObtenerIngresosPorTipoAsync(anio);
        }
        
        public string ObtenerTopProgramasRentables(int anio)
        {
            return base.Channel.ObtenerTopProgramasRentables(anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerTopProgramasRentablesAsync(int anio)
        {
            return base.Channel.ObtenerTopProgramasRentablesAsync(anio);
        }
        
        public string ObtenerBajasPorPrograma(int idPrograma, int anio)
        {
            return base.Channel.ObtenerBajasPorPrograma(idPrograma, anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerBajasPorProgramaAsync(int idPrograma, int anio)
        {
            return base.Channel.ObtenerBajasPorProgramaAsync(idPrograma, anio);
        }
        
        public string ObtenerMotivosBajasPorPrograma(int idPrograma, int anio)
        {
            return base.Channel.ObtenerMotivosBajasPorPrograma(idPrograma, anio);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerMotivosBajasPorProgramaAsync(int idPrograma, int anio)
        {
            return base.Channel.ObtenerMotivosBajasPorProgramaAsync(idPrograma, anio);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://webserviceudl.somee.com/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
